version: 1

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  
sphinx:
  configuration: docs/conf.py

python:
  version: 3.10
  install:
    - method: setuptools
      path: .
    - requirements: requirements.txt

dependencies:
  - python=3.10